site_name: ftrain
site_url: https://NischalPI.github.io/ftrain
site_description: Pytorch Lightning Convinence Library
site_author: Nischal Bhattarai
site_dir: html
repo_name: NischalPI/ftrain
repo_url: https://github.com/NischalPI/ftrain

plugins:
  - search
  - mkapi
  - awesome-pages
  - gen-files:
      scripts:
        - gen_pages.py

theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  #logo: img/logo.svg
  #favicon: img/favicon.png
  language: en


nav:
  - index.md
  - ... | glob=readme.md
  - ... | regex=scenarios/.+.md
  - API: mkapi/api/ftrain
  - Tests: mkapi/tests/tests

